name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install package and dependencies
      run: uv sync --dev

    - name: Install wasmtime thru package
      run: uv run python -m wasm_safe_eval.install_wasmtime    
    
    - name: Verify wasmtime installation
      run: wasmtime --version

    - name: Run tests
      run: make check